version: '3'
services:
  vpn:
    build: vpn
    volumes:
      - type: volume
        source: ~/openvpn
        target: /mnt/openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"