version: '3'
services:
  vpn:
    build: vpn
    volumes:
      - secrets:/secrets
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    network_mode: "host"
  ikea-tradfri-gateway:
    build: ikea-tradfri-gateway
    depends_on: 
      - vpn
    network_mode: "service:vpn"
volumes:
  secrets:
    external: true